# Generated by Django 2.2 on 2019-12-26 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_auto_20191222_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photo_app.Photomodel'),
        ),
    ]
