# Generated by Django 2.2 on 2019-12-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20191218_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to='user_app.UserModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
